### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by antgeo** [lewisbenge/hass-amber-electric#14]
Getting the following error running this sensor:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 292, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 451, in _async_add_entity
    entity.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 290, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 314, in _async_write_ha_state
    sstate = self.state
  File "/config/custom_components/amberelectric/sensor.py", line 100, in state
    return abs(self.calc_amber_price(self.amber_data.data.static_prices.b1.totalfixed_kwh_price, self.amber_data.data.static_prices.b1.loss_factor, current_price[0].wholesale_kwh_price))
IndexError: list index out of range

**Comment by antgeo** [comment]
Attached the json response from Amber's API
[amber.txt](https://github.com/lewisbenge/hass-amber-electric/files/5330672/amber.txt)

**Comment by lewisbenge** [comment]
Can you please see if the version on the dev branch (https://github.com/lewisbenge/hass-amber-electric/blob/dev/custom_components/amberelectric/ambermodel.py) resolve your issue? On Victorian postcodes it appears the Amber API had not included particular dates in random elements of the response causing null errors. This commit should fix that.

**Comment by antgeo** [comment]
Resolved. Thanks!
